### ISSUE TITLE
Clicking on an item takes you directly to task board but loses place when navigating back to Taskboard

### ISSUE THREAD

**Issue by l-brett** [AccentDesign/task_management#106]
When I navigate in the task board by clicking on a task:
![image](https://user-images.githubusercontent.com/2393431/50779405-22d19400-1298-11e9-92ba-216ba0b6c255.png)

I am presented with the task on the job board:
![image](https://user-images.githubusercontent.com/2393431/50779422-29f8a200-1298-11e9-87ab-5385af898de2.png)

However, pressing back loses my place in the list and any ordering applied:
![image](https://user-images.githubusercontent.com/2393431/50779442-3c72db80-1298-11e9-81ea-fa0902c7b1f1.png)

**Comment by thisdarktao** [comment]
See: #118. If this issue has other requirements, please reopen.
